### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by kiquenet** [fschwiet/fschwiet-boxstarter#1]
Great !

any updates about it in 2015? Is it obsolete fschwiet-boxstarter  or still working ?

I'm newbie about it.

How-to create a LAB Hyper-V VM

http://charbelnemnom.com/2014/04/build-a-step-by-step-hyper-v-and-vmm-lab-with-powershell/

How-to install apps silent and unattend in Dev Machine with powershell (chocolatey)

https://gist.github.com/vintem/6334646

Maybe interesting , combine Hyper-V VM and Chocolatey (or BoxStarter) for create Hyper-V VM from ISO (eg. Windows7, Windows8, Windows Server 2008/2012 R2), configure Server Features and Roles, change policies, set settings and configurations like Control Panel, IE Settings, modify machine.config, create appPools and websites in IIS, install certificates, install components like ODP.NET Oracle and others, install applications silent and unattend, etc. 

And DO those tasks programmatically using Powershell.

**Comment by fschwiet** [comment]
fschwiet-boxstarter is obsolete, but Boxstarter had some significant improvements since I wrote fschwiet-boxstarter.  Check out http://boxstarter.org/ for the latest on that.  I personally avoid Hyper-V so I cannot address that directly.  For some of the configuration tasks in Powershell you may want to look at Carbon (http://get-carbon.org/help/).

I'm not sure about the environment you're creating VMs into, but https://www.packer.io/ can be used to create custom baseline images (though I don't know about their windows /hyper-V support).  You may also find Puppet (http://puppetlabs.com/solutions/microsoft) or Chef useful.
